### ISSUE TITLE
How do you setup this package after I downloaded from bower in Angular?

### ISSUE THREAD

**Issue by klaoha06** [yaru22/angular-timeago#27]
It would be nice if you could write this on the readme file.

**Comment by yaru22** [comment]
Hi @klaoha06,

You can take a look at the [usage](https://github.com/yaru22/angular-timeago#usage) or the demo code.

Basically, you need:

1. Include the `angular-timeago` script (e.g. https://github.com/yaru22/angular-timeago/blob/master/demo/index.html#L41)
2. Specify the dependency on `angular-timeago` module (e.g. https://github.com/yaru22/angular-timeago/blob/master/demo/main.js#L4-L6)
3. Create a date object in the controller (e.g. https://github.com/yaru22/angular-timeago/blob/master/demo/main.js#L11)
4. Use it in the Angular template like `{{ dateObject | timeAgo}}` (https://github.com/yaru22/angular-timeago/blob/master/demo/index.html#L33)

Hope this helped.
