### ISSUE TITLE
Time is not being updated

### ISSUE THREAD

**Issue by Jarvey** [yaru22/angular-timeago#36]
Hi, thanks for this great plugin!

I have the problem that my time is not being updated

When I open your demo page and I leave it open the time is automatically updated every minute.
In my situation when I open my page the time is only being updated on page load but when I leave the page open for a few minutes time is not being updated anymore.
This is how I format my time in my page <time>{{activitie.start_date | timeAgo}}</time>
this time item is in a ng-repeat div (I don't know if that has something to do with it).

Thanks!

**Comment by yaru22** [comment]
It's hard to know what the exact problem is without reading the code. If you can create JSFiddle (http://jsfiddle.net/) or Plnkr (plnkr.co), I can take a look at it.

**Comment by Jarvey** [comment]
@yaru22 I found the solution.
I changed {{activitie.start_date | timeAgo}} to <time-ago from-time='{{ activitie.start_date }}'></time-ago>
I already tried this earlier but this time it seems to work.
If you like I can provide you with a dutch translation, can I copy it here in a comment or should I drop it somewhere else?

**Comment by yaru22** [comment]
Glad to hear you found the solution. If you'd like to add dutch translation, that would be great as well. Have you created a pull request before?
You can fork this repo, make the necessary changes and commit to your forked repo. Then you can create a pull request (https://help.github.com/articles/creating-a-pull-request/). Look forward to it =)

**Comment by 3x14159265** [comment]
@Jarvey having the same problem. How did you change {{activitie.start_date | timeAgo}}? seems parts of your last comment are skipped... Thanks in advance!

**Comment by Jarvey** [comment]
@3x14159265 Sorry for the late response. I edited my previous response.
