### ISSUE TITLE
Will it be cool if there is an option for displaying format date after a given 'timeago'?

### ISSUE THREAD

**Issue by ycmjason** [yaru22/angular-timeago#38]
I think it would be really cool if I could configure the filter so that it display a format date instead of timeAgo after 7 days. 

Do you think it's cool?

**Comment by yaru22** [comment]
@ycmjason Yeah, that's a great idea. I would welcome PR for that!

**Comment by yaru22** [comment]
Closing since it's addressed by @jgr3go.
