### ISSUE TITLE
Specify node entry point script

### ISSUE THREAD

**Issue by Tyller** [yaru22/angular-timeago#39]
can we have a patch release to npm containing this? Won't work with browserify properly otherwise.

**Comment by yaru22** [comment]
I don't use browserify anymore (using webpack these days) so I'm not sure if I know this correctly. By node entry point script, do you mean "main" field in package.json? If that's not what you meant, would you like to create a PR?

**Comment by Tyller** [comment]
Yes, I have test it and just adding the src/timeAgo.js to the main is enough to worked with browserify.

**Comment by yaru22** [comment]
Updated package.json. Let me know if the problem persists.

**Comment by Tyller** [comment]
I, yes I have check and he must be work, but, it missing the release on npm repo, because with browserify we used npm install angular-timeago for installing it.
Thank for your reactivity.

**Comment by yaru22** [comment]
Oops, I missed npm publishing. Just published now.

**Comment by Tyller** [comment]
everything is Ok, thanks for your work.
