### ISSUE TITLE
use provider to setup settings

### ISSUE THREAD

**Issue by fesor** [yaru22/angular-timeago#44]
Currently the only option to change settings is to use `settings` property of service.

I suggest to make this default settings private and add access to it via provider:

```javascript
angular
    .module('app', ['yaru22.angular-timeago'])
    .config(function (timeAgoProvider) {
        timeAgoProvider.setSettings({
        });
        timeAgoProvider.addTranslation('ru_RU', {
            prefixAgo: null,
            prefixFromNow: null,
            suffixAgo: 'назад',
            // ...
            })
        })
    })
;

```

**Comment by yaru22** [comment]
Thanks for the suggestion @fesor. Would you like to send me a pull request for that?

**Comment by Muximize** [comment]
+1

I use allowFuture, but there is no way now to set that in .config application-wide. So now I use `timeAgo.settings.allowFuture = true;` multiple times in multiple controllers :(

**Comment by yaru22** [comment]
Closing. See #61.
