### ISSUE TITLE
timeAgo filter directive not updating since angular 1.2

### ISSUE THREAD

**Issue by eparis** [yaru22/angular-timeago#54]
https://plnkr.co/edit/AbAMrP0Mm8Y92tBajTAD?p=preview

I prefer the filter directive style but it does not appear to update since angular 1.2. You can see all of the angular versions I tried in the plnkr. 1.2.28 works, but nothing more recent. (I didn't try angular 2+)

I see that https://github.com/yaru22/angular-timeago/issues/36 appears to be others reporting the same issue, but they just switched to the directive form, which still appears to work, instead of identifying the likely angular compatibility issue.

Thank you so much!

**Comment by astik** [comment]
It is still working with the unstable 1.3.0-beta.19 but no longer with the stable 1.3.0.

**Comment by astik** [comment]
Change can be found here : https://github.com/angular/angular.js/blob/master/CHANGELOG.md#130-rc2-tactile-perception-2014-09-16.
You can see the breaking change here : https://github.com/angular/angular.js/blob/master/CHANGELOG.md#breaking-changes-26
