### ISSUE TITLE
Basic directive does not update when 'from-time' value updates

### ISSUE THREAD

**Issue by eparis** [yaru22/angular-timeago#55]
https://plnkr.co/edit/6u3VxsF4VT1279PYaUMA?p=preview

Changing the `from-time` date does not update the text when using the 'basic' directive. It does work when using the filter directive.

Now I'm between a rock and a hard place because I can't use the filter directive (https://github.com/yaru22/angular-timeago/issues/54) and I can't use the basic directive.

**Comment by astik** [comment]
This problem is different from the filter one.
This one is due to the directive code which affects the fromTime value once and for all. By adding a watcher to it, the directive behaves the way you want.
PR is coming.
