### ISSUE TITLE
Easier way to add new languages

### ISSUE THREAD

**Issue by astik** [yaru22/angular-timeago#61]
Here is the way we add a new language dynamicly :

```js
angular.module('mfgApp').run(function(timeAgo) {
	timeAgo.settings.strings.zh_CN = { ... };
});
```

This is handy as we have a new file for each new language.
That way, angular-timeago sources can be available like this :

- src/timeAgo.js
- src/timeAgo-language-en.js
- src/timeAgo-language-en_US.js
- src/timeAgo-language-zh-CN.js
- src/timeAgo-language-fr.js
- ...

Adding a new language would be a matter of adding a new file and not modifying existing source code. It would be way easier to merge pull request.

In the above code example, languages are added at runtime (run phase), it would be better to do that at config phase.
The easier way to do so would be to set "timeAgo.settings" as an angular constant. New language would be added like this :

```js
// into timeAgo.js
angular.module('yaru22.angular-timeago').constant('timeAgoSettings', {
    refreshMillis: 60000,
    allowFuture: false,
    overrideLang : null,
    fullDateAfterSeconds : null,
    strings: { }
});

// into timeAgo-language-en_US.js
angular.module('yaru22.angular-timeago').config(function(timeAgoSettings){
   timeAgoSettings.strings['en_US'] = {
      ...
   }
});

// into timeAgo-language-it_IT.js
angular.module('yaru22.angular-timeago').config(function(timeAgoSettings){
   timeAgoSettings.strings['it_IT'] = {
      ...
   }
});
```

As a bonus, it would expose other angular-timeago settings as well =)

If you're interested, I gladly do a fork with that approach and PR it back to you.

**Comment by astik** [comment]
I have not check well other issues before posting (sorry). This issue is linked to #44.
Feel free to close this ticket if you prefer the provider approach over the constant approach =)

**Comment by yaru22** [comment]
Thanks for the suggestion @astik. Since we can't just add more and more languages to `src/timeAgo.js` and let the file size keep growing, your approach makes a lot of sense.
I think the constant approach is fine as well. I would love to merge the PR if you create one with the approach you described in this issue.

**Comment by yaru22** [comment]
Awesome work @astik!
