### ISSUE TITLE
Basic Filter timeAgo not updating

### ISSUE THREAD

**Issue by nasr18** [yaru22/angular-timeago#63]
I'm using Basic filter timeAgo `{{upcomingTask | timeAgo}}` and using future. I'm getting "50 minutes remaining" and showing "50 minutes remaining" until i refresh the page. Without refreshing the page, i need it to be autoupdate like "49 minutes remaining", "48 minutes remaining". And also I'm using `$interval` to update that timeago value after every 1 minute. but its not updating. How do i fix?
@yaru22

**Comment by yaru22** [comment]
Hi @nasr18, someone else has raised the same issue (#54). The filter doesn't seem to work since Angular 1.3. I haven't been following Angular for more than a year (using React these days) so I'm not sure what the fix is. If anyone has a fix for this, I would be pleased to merge a PR though.
