### ISSUE TITLE
Timezone aware

### ISSUE THREAD

**Issue by patrik7** [yaru22/angular-timeago#72]
Hi,

I am formatting the time in ISO format in UTC:
2016-05-31T19:22:29

I was hoping timeago would move this to client's machine timezone, before computing the offset.

Is there a way to switch this on? Possibly in combination with other angular plugin?

**Comment by astik** [comment]
Can you provide us a code example with the problem and what you are expecting ?
I don't understand your request right now =/

**Comment by patrik7** [comment]
Hi astik,

Of course, sorry for being too vague.

`<time-ago class="datetime" from-time="{{m.datetime}}" format='MM/dd/yyyy'></time-ago>`

m.datetime is a string in ISO format: %Y-%m-%dT%H:%M:%S

Now let's say timestamp it's 1pm UTC, the server will render 2016-06-01T13:00:00 as m.datetime

And currently is 2pm UTC (so one hour later), I would expect the time-ago to output "one hour ago".

However, my browser being on CEST, the time-ago actually outputs "3 hours ago". Seems like it assumes that the m.datetime timestamp is in my local TZ.

Patrik

**Comment by patrik7** [comment]
I solved it by rendering TZ into the string on server:
datetime: '2016-06-02T10:20:28.130509+02:00'

We can close this, thanks for your time

**Comment by astik** [comment]
No problem, glad you find your way out =)

**Comment by jeevasusej** [comment]
@patrik7, How did you solve? Can you paste the code?

**Comment by patrik7** [comment]
Hi @jeevasusej,

As mentioned, you need to make sure the plugin receives a TZ aware timestamp.

So instead of passing
`from-time="2016-06-02T10:20:28.130509"`

I passed:
`from-time="2016-06-02T10:20:28.130509+02:00"`

This way angular-timeago know in that TZ the timestamp is and can correctly show it in browsers/users TZ.

Hope that makes sense.
