### ISSUE TITLE
Project building for version 0.4.2

### ISSUE THREAD

**Issue by fauria** [yaru22/angular-timeago#75]
Regarding #74 I think the project was not built, so ```es_ES``` is unavailable in ```dist``` files.

**Comment by yaru22** [comment]
Ah, I just looked into it and it was happening because the language was set to `es_LA` inside `src/languages/time-ago-language-es_ES.js`. Fix is on the way.

**Comment by yaru22** [comment]
Published 0.4.3 with the fix. Thanks for reporting the issue @fauria.
