### ISSUE TITLE
Error: Invalid Date toISOString@[native code]

### ISSUE THREAD

**Issue by czmarcos** [yaru22/angular-timeago#84]
Hi, I'm using timeago with my ionic project. When I emulate on my browser the timeago is working fine, however I tested on a real device (iOS 9.2) and it is not working.

I have the following filter to convert dates:

```
app.filter('dateToISO', function() {
  return function(input) {
    input = new Date(input+'').toISOString();
		return  input ? input : '';
  };
})
```

I am fetching the dates from MySQL in this format as example: 
`2016-11-06 21:13:42`

And inside my template I am using time ago as this example:

`user answered {{ feed.QuestionAddedDate | dateToISO  | timeAgo }}`

Inside the logs on XCode is showing the following error:

```
2016-11-08 23:30:49.269 myApp[2897:1210215] ERROR: Error: Invalid Date
toISOString@[native code]
file:///var/mobile/Containers/Bundle/Application/1A748163-A9C3-486F-BB78-66E3EE8C18B3/myApp.app/www/js/app.js:34:43
fn
expressionInputWatch@file:///var/mobile/Containers/Bundle/Application/1A748163-A9C3-486F-BB78-66E3EE8C18B3/myApp.app/www/lib/ionic/js/ionic.bundle.js:27439:47
$digest@file:///var/mobile/Containers/Bundle/Application/1A748163-A9C3-486F-BB78-66E3EE8C18B3/myApp.app/www/lib/ionic/js/ionic.bundle.js:28987:43
$apply@file:///var/mobile/Containers/Bundle/Application/1A748163-A9C3-486F-BB78-66E3EE8C18B3/myApp.app/www/lib/ionic/js/ionic.bundle.js:29263:31
tick@file:///var/mobile/Containers/Bundle/Application/1A748163-A9C3-486F-BB78-66E3EE8C18B3/myApp.app/www/lib/ionic/js/ionic.bundle.js:24396:42

```
Thanks for any help!

**Comment by astik** [comment]
I can reproduce the problem with Safari (6.1.6), inside its console :
```
new Date("2016-11-06 21:13:42")
-> Invalid Date
```

It's working fine with Chrome.

This is a problem from Safari JS engine, not an angular-timeago issue.

**Comment by astik** [comment]
You can find more information on this SO : http://stackoverflow.com/questions/16616950/date-function-returning-invalid-date-in-safari-and-firefox
