### ISSUE TITLE
Update the dist folder

### ISSUE THREAD

**Issue by raffaelecalza** [yaru22/angular-timeago#96]
Recently I fixed a punctuation error in the `hour` field of italian strings but in the dist folder both files timeago.js and the minified file still have the error.

Here is the commit 0de0131

Should I open a new pull request where there is the updated string in both files?

**Comment by astik** [comment]
The dist folder is updated when there is a new release.
Wait for @yaru22 to do a new release and everything should be fine.
In the meantime, sorry for the delay.

**Comment by yaru22** [comment]
Sorry about the delay. Just published the latest version. Let me know if you still see the problem.
