### ISSUE TITLE
Do I need both JS files from the dist folder?

### ISSUE THREAD

**Issue by ianhd** [yaru22/angular-timeago#97]
The `dist` folder has multiple JS files. Do I need both `angular-timeago-core.min.js` and `angular-timeago.min.js`? Do I need to include both for this library to work? Looking for to use it in its most basic way. Thanks.
`

**Comment by astik** [comment]
Hi,
You don't need to include all dist files into your project.
As stated at https://github.com/yaru22/angular-timeago#language-pickup, you can bundle core + all languages with a single file or you can pickup core + languages you want. This way, you don't package language which are unneeded for your project.
